### PR TITLE
DEV | Fix missing closing bold delimiters

### PR DESCRIPTION
**Pull request by aloisdg**
(I am not sure about your commit message style)

### CODE REVIEW

**Comment by mseknibilel** [comment]
Thx for your pull request, the commit message style is more of a habit, open for any new suggestion

**Comment by aloisdg** [comment]
For my serious projects, I mostly use the Angular logic with [commitizen](https://github.com/commitizen/cz-cli).

**Comment by mseknibilel** [comment]
cool, i'll take a look at !

**Comment by aloisdg** [comment]
:)

**Pull request merged**
